const cardListActionTypes = {
  FETCH_START_GIFTS_REQUEST: 'FETCH_START_GIFTS_REQUEST',
  FETCH_START_GIFTS_SUCCESS: 'FETCH_START_GIFTS_SUCCESS',
  FETCH_START_GIFTS_FAILURE: 'FETCH_START_GIFTS_FAILURE',
  FETCH_MORE_GIFTS_REQUEST: 'FETCH_MORE_GIFTS_REQUEST',
  FETCH_MORE_GIFTS_SUCCESS: 'FETCH_MORE_GIFTS_SUCCESS',
  FETCH_MORE_GIFTS_FAILURE: 'FETCH_MORE_GIFTS_FAILURE'
};

export default cardListActionTypes;